# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

pool:
  vmImage: windows-2022
  
variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:

- task: UseDotNet@2
  displayName: Use .NET 7.0
  inputs:
    packageType: 'sdk'
    version: '7.0.x'

- task: CmdLine@2
  inputs:
    script: 'dotnet workload install maui'

- task: DotNetCoreCLI@2
  name: "Build"
  inputs:
    command: 'build'
    projects: 'TimeTracker.sln'

- task: DotNetCoreCLI@2
  name: "Test"
  inputs:
    command: 'test'
    projects: 'TimeTracker.sln'

- task: DotNetCoreCLI@2
  name: "Restore"
  inputs:
    command: 'restore'
    projects: 'TimeTracker.sln'